on:
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: scala-steward-org/scala-steward-action@v2.63.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        author-email: "2517319+scala-steward-bot@users.noreply.github.com"
        author-name: "scala-steward-bot"
